services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - type: bind
        source: ..
        target: /workspace
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"